name: Build and package project

on:
  schedule:
    # Uruchamianie raz w tygodniu w poniedziałek o godzinie 00:00 UTC
    - cron: '0 0 * * MON'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: Task0  # Checkout the Task0 branch

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: ./installResources.sh
      shell: bash

    - name: Checkout main branch code
      uses: actions/checkout@v3
      with:
        ref: main  # Checkout the main branch

    - name: Display environment info
      run: |
        python --version
        pip --version
        uname -a
      shell: bash

    - name: Build executable
      run: |
        pyinstaller --onefile project.py
      shell: bash

    - name: List build directory contents
      run: |
        ls -la
        ls -la dist
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: project-executable
        path: dist/project.exe
